package com.codecollab.model;

/**
 * UserSession — A simple data object (POJO) representing a connected user's session.
 *
 * WHAT IS A POJO?
 * ---------------
 * POJO stands for "Plain Old Java Object". It's a simple class that just holds data
 * (like a container/box) with no complex logic. It has fields (variables) and
 * getter methods to read those fields.
 *
 * WHAT THIS CLASS STORES:
 * -----------------------
 * When a user connects to a room in CodeCollab, we need to remember three things:
 *   1. sessionId - A unique identifier for this WebSocket connection (like a ticket number)
 *   2. userName  - The display name the user chose (e.g., "Alice")
 *   3. roomId    - Which room the user is in (e.g., "abc-123-def")
 *
 * This class bundles those three pieces of information together so we can pass
 * them around easily in the code. For example, when we need to know who is in
 * a room, we get a list of UserSession objects.
 *
 * WHY ARE FIELDS "final"?
 * -----------------------
 * The "final" keyword means these values cannot be changed after the object is
 * created. This is intentional — once a user session is created with a specific
 * sessionId, userName, and roomId, those values should never change. If a user
 * switches rooms, we create a NEW UserSession object rather than modifying the old one.
 * This makes the code safer and easier to reason about.
 *
 * USAGE EXAMPLE:
 * --------------
 *   UserSession session = new UserSession("abc-123", "Alice", "room-456");
 *   String name = session.getUserName();  // Returns "Alice"
 *   String room = session.getRoomId();    // Returns "room-456"
 */
public class UserSession {

    /** A unique identifier for this WebSocket connection (UUID format, e.g., "550e8400-e29b-41d4-a716-446655440000"). */
    private final String sessionId;

    /** The display name chosen by the user when joining a room (e.g., "Alice"). */
    private final String userName;

    /** The unique identifier of the room this user belongs to (UUID format). */
    private final String roomId;

    /**
     * Creates a new UserSession with the given session ID, username, and room ID.
     *
     * This constructor is called when a user sends a "join" message via WebSocket.
     * The RoomService creates a new UserSession and stores it in memory.
     *
     * @param sessionId The unique WebSocket session identifier (generated by the server).
     * @param userName  The display name chosen by the user.
     * @param roomId    The ID of the room the user is joining.
     */
    public UserSession(String sessionId, String userName, String roomId) {
        this.sessionId = sessionId;
        this.userName = userName;
        this.roomId = roomId;
    }

    /**
     * Returns the unique session identifier for this WebSocket connection.
     * Used to look up the actual WebSocket connection object when we need
     * to send a message to this specific user.
     *
     * @return The session ID string.
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Returns the display name of this user (e.g., "Alice").
     * Used in the frontend to show who is connected and who sent chat messages.
     *
     * @return The user's display name.
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Returns the room ID that this user belongs to.
     * Used to determine which room to broadcast messages to.
     *
     * @return The room ID string.
     */
    public String getRoomId() {
        return roomId;
    }
}
